### ISSUE TITLE
code suggestion - anyhow

### ISSUE THREAD

**Issue by ArjixWasTaken** [StratusFearMe21/jonahbox#1]
I suggest using anyhow to make error ~~handling~~ ignoring prettier to the eye.

https://docs.rs/anyhow/latest/anyhow/

Instead of calling `.unwrap()` all the time, you'd be using the `?` operator, it is basically like `.unwrap()` but in case there is an error it will return that error.

So the function signature wherever this is used will have to change to `anyhow::Result<T>` where `T` is the original return type.

For example, `load_handler` would change in the following way

```diff
- ) -> String {
+ ) -> anyhow::Result<String> {
```

```diff
-            let response: String = state
-                .http_cache
-                .client
-                .get(&url)
-                .send()
-                .await
-                .unwrap()
-                .text()
-                .await
-                .unwrap();
+            let response = state.http_cache.client
+                .get(&url).send().await?
+                .text().await?;
```

**Comment by ArjixWasTaken** [comment]
Note that I did not test the code, so don't take my word w/o salt.

**Comment by StratusFearMe21** [comment]
Yep, this was in my mental roadmap. My goal was to get an implementation working first (which it fully is as of yesterday), and then pretty it up from there. This refactor shouldn't be too difficult, but it is needed

**Comment by StratusFearMe21** [comment]
BTW, using `anyhow` in this way is a footgun. This would turn errors that were somewhat useful, and contained a line number, to just the raw error, which can be really difficult to debug. Like this really bad error:
```
No such file or directory (os error 2)
```
You need to add context to `anyhow` errors so that you can trace back where your code went wrong, and the parameters that caused the error. That way you can get an error like:
```
Error: Failed to read instrs from ./path/to/instrs.json

Caused by:
    No such file or directory (os error 2)
```
 *This* is the power that `anyhow` gives you, and `unwrap` doesn't.
```diff
-            let response = state.http_cache.client
-                .get(&url).send().await?
-                .text().await?;
+            let response = state.http_cache.client
+                .get(&url)
+                .send()
+                .await
+                .with_context(|| format!("Request failed to {}", url))?
+                .text()
+                .await
+                .with_context(|| format!("Resource at {} failed to read to a String", url))?;
```

**Comment by StratusFearMe21** [comment]
I got a 404 error to look like this, 
![20240529_17h13m36s_grim](https://github.com/StratusFearMe21/jonahbox/assets/57533634/b3cc31f9-d440-4fb7-b745-2da4210e5a6b)
(I'm taking this issue far too seriously :smile: )

**Comment by StratusFearMe21** [comment]
The final result of this endeavor (This is what a 404 looks like now):
![20240529_22h40m55s_grim](https://github.com/StratusFearMe21/jonahbox/assets/57533634/36f694c9-83ba-44d7-8678-e3033a321b4d)
